### ISSUE TITLE
Floating tabs looks too cramped on Linux

### ISSUE THREAD

**Issue by bbhtt** [bmFtZQ/edge-frfox#118]
### Description

The tab height and font size seems too small and doesn't match the screenshots in README. Not sure if this a bug

Using theme directly from git at 28e7b8a05a8a09c1cb3a4333d8a797c0139d005b

**Include screenshot / video recording if possible.**

![image](https://github.com/bmFtZQ/edge-frfox/assets/62639087/d42bffea-16bc-423a-b4d1-50dd76686d44)

![image](https://github.com/bmFtZQ/edge-frfox/assets/62639087/3b6aeb0e-43c4-4e4f-8b02-ddc098c1defb)

### Configuration
* Firefox Version: 121
* OS: (eg. Windows 11, macOS 14, Linux with GNOME 45, etc.) Fedora 39
* Tweaks enabled: 
  * `uc.tweak.floating-tabs`

**Comment by bmFtZQ** [comment]
The size of the tabs in both operating systems are `32px` tall, and the fonts used for the label both have a size of `12px`.

The difference you are seeing is probably due to differences in the fonts itself. Both fonts have the same cap-height in all images, though the there is a difference in the height of the lowercase letters as seen below, where Fedora's font has smaller lowercase letters:

![bitmap](https://github.com/bmFtZQ/edge-frfox/assets/62812711/acf22ffa-f9f3-427f-930d-8b62e9aab2ba)

![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/f60cf6ea-ff8f-40f0-95b3-cb72d48aa04e)

![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/ff8c5083-3ba6-418a-891c-2eb0265742c4)

**Comment by bbhtt** [comment]
I made both larger in my fork. Thanks. Probably looked small in my eyes.
