### ISSUE TITLE
 Fix the color of elements to match with the rest of the theme + rounded corners issue.

### ISSUE THREAD

**Issue by ghost** [bmFtZQ/edge-frfox#121]
### Description
**Change background color of the inspector tool in Firefox to match Edge.**
| <img src="https://github.com/bmFtZQ/edge-frfox/assets/107957769/e6f3ff4e-986b-433b-90ec-019e407efd4d" height="400"> <img src="https://github.com/bmFtZQ/edge-frfox/assets/107957769/b74f1bbf-5f1d-45f8-b9a0-f6b16091fd22" height="400"> | 
|:--:| 
| *Edge On The Left, Firefox On The Right* |

**Change the background color of several settings menu popup's to match Edge.**
| <img src="https://github.com/bmFtZQ/edge-frfox/assets/107957769/6f86adf5-d8f5-494b-a6e5-0ae0dfcb2a75" width="200"> <img src="https://github.com/bmFtZQ/edge-frfox/assets/107957769/e35f7cf8-c7ef-4269-9ea0-68247750029b" width="200"> <img src="https://github.com/bmFtZQ/edge-frfox/assets/107957769/091f3933-179e-4ca9-847d-097ad55f9645" width="200"> | 
|:--:| 
| *Settings Menu, Full screen and Remove Extension Popup* |

When using `uc.tweak.rounded-corners` I've noticed that on some websites the border radius doesnt seem to work.
| <img src="https://github.com/bmFtZQ/edge-frfox/assets/107957769/cf7a55c5-384d-479b-bc9f-5704754ab9da" width="200"> <img src="https://github.com/bmFtZQ/edge-frfox/assets/107957769/ed8b7f32-9a53-479a-8e75-a79ff8a46196" width="200">  | 
|:--:| 
| *Normal On Left, Bugged On Right* |

### Configuration
* Firefox Version: 120.0.1
* OS: Windows 11

**Comment by bmFtZQ** [comment]
I probably won't make changes to the devtools theme as I don't think most people will use it enough and personally I am fine with the existing theme.

I plan on changing the pop-up colours eventually, the changes that were made in Firefox 119.0 to support `light-dark()` certainly make that easier to implement.

The rounded corners issue cannot be fixed as far as I know. It is caused by websites that use `backdrop-filter` based on some testing. Twitter/X uses `backdrop-filter` for the post/sort header, disabling `backdrop-filter` fixes the rounded corners issue.

![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/7d7e4e5d-4bf3-4882-ba33-bc353eed603e)

After applying this CSS rule to `userContent.css` or Stylus extension:
```css
* {
  backdrop-filter: none !important;
}
```

![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/0bfe9baa-494a-4ce8-a92c-002fb7444766)
