### ISSUE TITLE
FF 133.0b2 break windows os 's hide-tab-bar.css windows control button

### ISSUE THREAD

**Issue by rainbowflesh** [bmFtZQ/edge-frfox#167]
The issue:
![QQ20241031-174618](https://github.com/user-attachments/assets/d08a3abd-e3b4-4ff2-ba7f-735779169e11)
A quick debug show looks like `nav-bar browser-toolbar` masked over control button:
![QQ20241031-174739](https://github.com/user-attachments/assets/93200196-7d50-492c-ab0e-15dede5766e4)

**Comment by rainbowflesh** [comment]
A WIP simple fix is change:
https://github.com/bmFtZQ/edge-frfox/blob/e36eec06b0d1e4ecef1e6052ecd132efbb732e58/chrome/tweaks/hide-tabs-bar.css#L85
```css
margin-right: 140px !important;
padding-inline-end: var(--uc-titlebar-drag-space) !important;
```
![QQ20241031-175219](https://github.com/user-attachments/assets/27e44deb-97f6-44ea-8d7d-1848761196ea)

**Comment by bmFtZQ** [comment]
Mozilla added window controls to the `#nav-bar` in Firefox 133, so I've made some modifications to just display those window controls if they exist, otherwise fallback to positioning the window controls from the `#TabsToolbar` on older versions of Firefox.

![image](https://github.com/user-attachments/assets/68dd1ef6-1d2a-403e-a456-09b7b48cc764)

This way the window controls cannot be hidden by the `#nav-bar` element as they are inside of it, and can probably prevent some similar issues in the future.

The issue here is similar to something [I fixed earlier this year](https://github.com/bmFtZQ/edge-frfox/commit/123cff422c9225d314e1d717f51fccc90a56ff4d). Though Mozilla removed the `#Titlebar` element and applied the same declaration to the `#TabsToolbar`, so this would have also fixed the issue:

```css
:root[tabsintitlebar] #TabsToolbar {
  will-change: auto !important;
}
```
