### ISSUE TITLE
Explanation for a tweak

### ISSUE THREAD

**Issue by IkelAtomig** [bmFtZQ/edge-frfox#52]
Tweak : `uc.tweak.disable-drag-space`
Description in Readme : disable drag space above tabs

I don't see any space above tabs in Firefox both in Maximized and minimized windows. Which space are you referring to ?

**Comment by bmFtZQ** [comment]
This reduces/removes the space above the tabs and doesn't apply to maximised windows as the space is removed regardless of the setting, leaving the top of the tabs touching the screen border.

Tweak Enabled:

![Screen Shot 2022-07-26 at 23 21 32](https://user-images.githubusercontent.com/62812711/181045887-d5f08765-27b2-4fbe-b214-cd86d7659e62.png)

Tweak Disabled:

![Screen Shot 2022-07-26 at 23 21 20](https://user-images.githubusercontent.com/62812711/181045992-9411f7e5-ae6f-4c08-8327-7f5a900dde1c.png)

This tweak only exists because this used to be an option in older versions of Firefox (you could find it in the 'Customise Firefox' screen, but was removed with Proton)

**Comment by EdwardLangdon** [comment]
I understand now, Thanks. Please define this in readme too and close the issue.

**Comment by IkelAtomig** [comment]
@bmFtZQ

**Comment by IkelAtomig** [comment]
> Please define this in readme too and close the issue.

@bmFtZQ

**Comment by bmFtZQ** [comment]
I've updated the README file to include a more detailed description:

> ### Remove extra space at the top of the window
> Removes the additional space at the top of the window above the tabs that
> appears when the window is not maximised. Enabling this will cause the tabs to
> touch the top edge of the window at all times.
>
> `uc.tweak.disable-drag-space`
