### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#55]
**Description**

Add support for custom background images like in Edge for New tab.

Note : I am using Background images in my own fork but not in an intuitive GUI way. Maybe you can see it for reference.

**Comment by bmFtZQ** [comment]
I've added support for background images, just enable the tweak `uc.tweak.newtab-background` and add an image named `background-0.(jpg/png)` into the `chrome` folder. Optionally you can use a second image for dark mode by adding an image named `background-1.(jpg/png)`.

![light](https://user-images.githubusercontent.com/62812711/182775161-c9b9e522-edb5-4a8a-8b5a-a3fc9d5001c3.png)

![dark](https://user-images.githubusercontent.com/62812711/182775189-67fa1592-133f-4302-8dbd-2f4e9598c5e0.png)

**Comment by EdwardLangdon** [comment]
I am okay with the tweak and loading Background images. 

What happens if I add Multiple Images ?

Will it come in an order like a Slideshow, If so cool.

I think it is better to put the images inside a New subfolder named `img` or something like that to have tree structure clean.

**Comment by bmFtZQ** [comment]
> What happens if I add Multiple Images ?

You can only use two images, `background-0` and `background-1` (for dark mode only).

In dark mode, if there is no `background-1` image supplied then `background-0` will be displayed instead.

Technically a `background-X.jpg` and `background-X.png` will both be displayed, but the jpg image will always be on top, so there would no point in doing so. Although you can mix the formats (`jpg` for `bg-0` and `png` for `bg-1` or vice versa).

> Will it come in an order like a Slideshow, If so cool.

A slide show could be theoretically possible but Firefox doesn't support animating the `background-image` property.

> I think it is better to put the images inside a New subfolder named `img` or something like that to have tree structure clean.

I just put the images in the `chrome` folder because that makes it easier to setup, so the user doesn't have to create any extra folders (and the repository wont have any empty folders). But anyway it's only two files, so the `chrome` folder wont really be cluttered.

**Comment by EdwardLangdon** [comment]
Thanks for the explanation. I will close this issue now. And open a separate one for Slideshow.
