### ISSUE TITLE
Firefox 113 Compatibility

### ISSUE THREAD

**Issue by ghost** [bmFtZQ/edge-frfox#88]
A few things are broken in Firefox 113, like the shield icon in the address bar and the centering of some icons, and the centering of icons within the right click menu (back, forward and bookmark).

Some of the text is also cut off by ... when its too long for the menu.

**Comment by GalacticHog** [comment]
I've changed an about:config setting to make the fonts a bit thicker so its entirely possible this is just on my end, if you don't see it in your browser I'm sorry for the misdirection, and thanks for the fixes, much appreciated, didn't wanna say goodbye to this amazing theme!

**Comment by GalacticHog** [comment]
A minor fix for the fix that might be helpful, there's an tab highlight issue when hovering over an unselected tab that is to the right of the current tab that can be fixed by adding this:

.tabbrowser-tab[selected]{
  position: relative;
  z-index: 1;
}

to "tabbar.css"
I've done it myself and confirmed it works but you might want to consider adding this to the theme
